# Generated by Django 2.2.3 on 2019-07-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
                ('pista_banco', models.TextField()),
                ('pista_bar', models.TextField()),
                ('pista_penhores', models.TextField()),
                ('pista_charutaria', models.TextField()),
                ('pista_chaveiro', models.TextField()),
                ('pista_docas', models.TextField()),
                ('pista_carruagens', models.TextField()),
                ('pista_farmacia', models.TextField()),
                ('pista_hotel', models.TextField()),
                ('pista_livraria', models.TextField()),
                ('pista_museu', models.TextField()),
                ('pista_parque', models.TextField()),
                ('pista_syard', models.TextField()),
                ('pista_teatro', models.TextField()),
                ('solucao', models.TextField()),
            ],
        ),
    ]
