# Generated by Django 2.2.3 on 2019-07-29 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pista_banco', models.BooleanField()),
                ('pista_bar', models.BooleanField()),
                ('pista_penhores', models.BooleanField()),
                ('pista_charutaria', models.BooleanField()),
                ('pista_chaveiro', models.BooleanField()),
                ('pista_docas', models.BooleanField()),
                ('pista_carruagens', models.BooleanField()),
                ('pista_farmacia', models.BooleanField()),
                ('pista_hotel', models.BooleanField()),
                ('pista_livraria', models.BooleanField()),
                ('pista_museu', models.BooleanField()),
                ('pista_parque', models.BooleanField()),
                ('pista_syard', models.BooleanField()),
                ('pista_teatro', models.BooleanField()),
            ],
        ),
    ]
